version: 2

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install npm dependencies
          command: npm ci

      - run:
          name: Run all tests
          command: npm run test ts-configurable

      - codecov/upload:
          file: coverage/
