version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install npm dependencies
          command: npm install

      - run:
          name: Check if all files are formatted correctly
          command: npm run format:check

      - run:
          name: Check for linting rule violations
          command: npm run lint

      - run:
          name: Run all tests
          command: npm run test ts-configurable

      - store_test_results:
          path: test-results/

      - store_artifacts:
          path: test-results/

      - codecov/upload:
          flags: unittests
          file: coverage/libs/ts-configurable/lcov.info
